### ISSUE TITLE
In chrome laggy

### ISSUE THREAD

**Issue by stafast** [drien/jquery-flipster#120]
Hello,

in chrome (v60) is flipster really laggy for me and a friend.
Some ideas why?

Greets André

**Comment by PiyushPradhan** [comment]
Yes, same here. It's the third section in my website. When I start scrolling the website, the first 2 sections scroll smoothly, as soon as the flipster section starts coming up it starts lagging, cant reach on the flipster section smoothly. I guess it us because of the mouse wheel side scroll. How do I disable scrolling with mouse wheel for jquery.flipster and add next and prev button, clicking on which will control the sliding. 
Refer the screencast : https://www.screencast.com/t/dZfIcPu6j
Website Link: http://videonx.com 
I updated the jquery.flipster,min.js with the latest one. Please advice.

**Comment by coax** [comment]
Did you see this https://github.com/drien/jquery-flipster/issues/119?

**Comment by drien** [comment]
So as far as I can tell this comes from the `-webkit-box-reflect` CSS property being applied to the items in the coverflow–Chrome is really slow at rendering it. It's a non-standard property and the MDN says the effect can be reproduced with the CSS `element()`  function, so we should probably do that, but I haven't looked much further.

In the meantime if you're ok with not having the box reflection effect you can easily override it in your own css:
```css
.flipster--coverflow .flipster__item__content {
    -webkit-box-reflect: inherit;
    box-reflect: inherit;
}
```

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
