### ISSUE TITLE
Coverflow Negative margin issue when all items are dynamically removed and new items are inserted

### ISSUE THREAD

**Issue by tyaginboston** [drien/jquery-flipster#125]
I am using Default Coverflow style Flipster. It Doesn't inject negative margin to list item when all Flipster item is removed and inserted in runtime. Even after using the Index method. I have to right inline Negative margin to make it work. Also Noticed when the browser is resized plugin resets and inject the correct Negative margin to the Flipster items

Here is the PEN url
https://codepen.io/shraftali/pen/rJMYEG

<img width="1407" alt="screen shot 2018-02-06 at 3 24 22 pm" src="https://user-images.githubusercontent.com/6991376/35882535-89df016c-0b52-11e8-88a1-18cbf1413825.png">
<img width="1386" alt="screen shot 2018-02-06 at 3 23 44 pm" src="https://user-images.githubusercontent.com/6991376/35882536-89ec98ae-0b52-11e8-8dd2-50732f349f35.png">

**Comment by wester9208** [comment]
The reason this is happening is because the flipster is initialized for div which are display none or which have height 0. Also this can be caused if flipster is already initialized. So to solve it you can either initialize it only before it is shown And please keep in mind not to initiliaze this again if already initialized

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
