### ISSUE TITLE
Broken in Chrome, Edge, Safari

### ISSUE THREAD

**Issue by hsnyc** [drien/jquery-flipster#157]
Hello, I noticed today our slider appears to be broken after working great for several years.  It looks to be working fine in FireFox though (desktop and mobile versions). I have updated to the latest version of the library v1.1.7 ... thought a recent update to Chrome could be the cause but I see your demo site is working fine... is there anything we are missing?.. any help is appreciated. Thank you!

https://medmonitor.healthesystems.com/welcome/

**Comment by drien** [comment]
Hi @hsnyc, it looks like there's a css rule from the Oxygen css framework on your page that's taking precedence and making the items in the carousel `display: list-item` instead of `display: inline-block`:
<img width="614" alt="image" src="https://user-images.githubusercontent.com/2391118/126354994-e89c0232-3cdc-48c7-af61-ecf70927c71f.png">

When I untick that in the inspector (and resize the page to trigger flipster reflow), the slider works as expected. I'd suggest adding this to your css:
```css
.flipster__item { 
  display: inline-block !important; 
}
``` 

I may choose to add that to the flipster css to make sure this problem can't happen elsewhere, but I haven't worked on this in a while and don't have time to test and release a new version anytime soon.

**Comment by hsnyc** [comment]
Thank you so much for the reply @drien. This fixed our issue.
