### ISSUE TITLE
Responsive carousel mode

### ISSUE THREAD

**Issue by cajrix** [drien/jquery-flipster#55]
dear, 

is it possible to use this plugin as responsive carousel (need to resize images when resizing windows)
+ carousel mode like in old version (so no jump to first item as its now) 
i mean this style http://brokensquare.com/Code/jquery-flipster/demo/

**Comment by shshaw** [comment]
@cajrix You should be able to set your responsive styles in CSS to help everything fit correctly on all screen sizes. For instance `.flip-item { max-width: 60%; } .flip-item img { max-width: 100% }` so that multiple items will be shown on smaller screen sizes and the images will scale. Flipster is set to resize itself whenever the window is resized in case someone changes their browser window or flips from landscape to portrait on a mobile device.

You can set the look using the `style` option to `carousel` or `coverflow` when you initialize Flipster.

Version 1.0 is coming soon, and it may change a few ways things are done (for the better!), but this advice should still apply :-)
