### ISSUE TITLE
Internal loop when flipster is loaded using AJAX request

### ISSUE THREAD

**Issue by farlop** [drien/jquery-flipster#79]
I have updated flipster from 2015-03-06 build to current one and notice Flipster is not working after that. After some debugging it seems related to a internal looping between 'center' and 'resize' functions on initialization. I think that it's due to the width of the container being 0, preciselly the condition in line 387:

`if ( !_containerWidth || _itemOffsets[_currentIndex] === undefined ) { resize(true); }`

If I change the first part to _containerWidth === undefined, the loop is not produced, but the component is not well drew until a resize event.

**Comment by shshaw** [comment]
Do you get the same `Uncaught RangeError: Maximum call stack size exceeded` as mentioned in #74 ? If so, you may have found the solution to both!

**Comment by ewhitmire** [comment]
I am also seeing the stack size exceeded error. I think it's due to the dimensions of the container not being set by the time flipster is initialized. Perhaps waiting until after everything has rendered may fix the problem. I'm ussing less.js and it adds a `body { display: none !important }` which I think is causing the 0 width and height.

In my case, I fixed this by adding:`        
  <script>
          less = {
            async: true
          };
        </script>
` before loading less.js.

**Comment by shshaw** [comment]
Merging this with #74

**Comment by shshaw** [comment]
Fixed in [1.1.1](https://github.com/drien/jquery-flipster/releases/tag/1.1.1). If no width is given, a `setInterval` is run every 500ms to trigger the `resize` event again instead of running in an infinite loop. 

If you want it to run right away and know when it will be visible, you can simply call the `jump` method with no parameter and resize will be triggered as usual.

Don't run this code with the last version of Flipster, it will crash your browser, but is perfectly fine in 1.1.1!

```js
$('body ').hide();

var flipContainer = $('.flipster').flipster();

setTimeout(function(){ 
   $('body').show();
   flipContainer.flipster('jump');
},1800);

```

**Comment by mangowi** [comment]
I am also getting the Uncaught RangeError: Maximum call stack size exceeded and my browser crashes, after AJAX call.
I am using v 1.1.1.

**Comment by locale3** [comment]
@shshaw https://stoppropagationpure.github.io/odBDyjN/
