### ISSUE TITLE
HTML interaction on past and future items

### ISSUE THREAD

**Issue by herecomesthesun** [drien/jquery-flipster#82]
When `flipster_item--past` or `flipster_item--future` contain interactive HTML elements, they still trigger interaction responses (hover states, clickable buttons, etc.). Not sure if this intended behavior.

![image](https://cloud.githubusercontent.com/assets/11964962/14577114/9915bbc2-0324-11e6-9471-817a814c6711.png)

In the above example, the add to cart button works, the hover states (orange highlight) work, and the qty field is also interactable.

EDIT: This workaround should work:
`.flipster__item--future *, .flipster__item--past * { pointer-events: none; } `

**Comment by solarroger** [comment]
Actually, a slightly modified CSS DOES work:

`	 .flipster__item--future *, .flipster__item--past * {
		 pointer-events: none;
	 }
`

Navigation and scrolling still work that way, but nothing in the HTML of that item will interact until it becomes the current item.

Should I make this a pull request?

**Comment by shshaw** [comment]
`:hover` effects, are allowed, yes, but if you have Flipster's  `click` option set to true, clicking the non-current flipster item should only switch to the item, not whatever the default action would be.

If you need to disable `:hover` states, then target specifically with CSS so that only the current item's content will have the hover state,

```
.flipster__item--current .button:hover { background: orange; }
```

Or use `pointer-events: none` like you have, though that may disable the click to switch option.
