### ISSUE TITLE
Insert at beginning behaves strangely

### ISSUE THREAD

**Issue by eriqjaffe** [drien/jquery-flipster#85]
I'm working on a coverflow that can have thousands of images - to keep memory usage reasonable I only want to load the visible covers at any given time and then add and remove covers as needed depending on the direction of travel.  I've got all that logic settled already, but I'm running into some strange display behavior when trying to insert an image at the beginning of the flow - the image is added, but the selected image moves off-center and there is a gap in between it and the beginning of the flow.  If I navigate towards the end of the flow enough the beginning of the flow rights itself.

I've set up a codepen demonstrating the issue (just click the buttons to call the insert and append logic):

http://codepen.io/eriqjaffe/pen/RadGLZ

Note that appending images to the _end_ of the flow works as expected, it's just trying to add them to the beginning.

**Comment by shshaw** [comment]
Interesting. Thanks for putting together the demo. I'm getting the same results in Chrome 50.

It looks like Flipster is offsetting all the existing items by the width of the first item. Likely an issue with the `resize` function, and may be related to image dimensions not being available when it's first added.

**Comment by stokesbga** [comment]
This is similar problem as described in #68. I am getting the gap spacing/off centered elements by doing this:
1. Adding N elements (one at a time, each time calling index) 
2. Deleting M elements. 
3. Re-adding any elements until N. The elements created in previously existing spots have broken spacing. 
4. Once N+1 elements are added, the spacing is fixed for the whole list again.

#68 was mainly talking about how adding new elements had animation 'jitter' (not the expected translateX animation) - but spacing was fine. This happens when they are created for the FIRST time - not in previous spots.

**Comment by stokesbga** [comment]
@shshaw What is the purpose of `skipTransition`?

**Comment by shshaw** [comment]
skipTransition is to prevent the CSS transitions during the initial setup &
centering.

Haven't had a chance to inspect the code yet to isolate this issue. If you
find anything, please let me know or offer a pull request.

**Comment by mariavilaro** [comment]
I had a similar problem. I was changing all the elements of the flipster, and there was an spacing between the elements after calling index. I solved it after hours of fiddling, by adding just a line at the end of the index method, just before `return self`:

    resize(true);

**Comment by drien** [comment]
This repository is going into very-low-maintenance mode and declaring backlog bankruptcy
